### ISSUE TITLE
Move to injectable

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#105]
Because when using kiwi we still need to register everything by hand. 

This is not always easy and can be easily forgotten.

For a long time, we have been looking for a Dagger alternative in dart. It seems that injectable is the best option outthere. 
https://pub.dev/packages/injectable
https://pub.dev/packages/injectable_generator

Kiwi can be removed from the flutter-template.

**Comment by ikbendewilliam** [comment]
rename and strip script might fail, To check after implementation
