### ISSUE TITLE
Update provider widget to support theme & localization

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#126]
![image](https://user-images.githubusercontent.com/21172855/102755330-87476a00-436e-11eb-88c4-f247a355320a.png)

**Comment by ikbendewilliam** [comment]
What we could do is add an extension to context for both theme and localization. That way you can do `context.colorsTheme.backgroundDark` and `context.localization.todoTitle`. The drawback is that VSCode (I think it is the same for Android Studio) doesn't know where extensions come from and you need to manually import the file (or something else from that file). 
Another solution is to overwrite/add mixins to `StatefulWidget` and `State` and have the localization & theme added in the build method, drawback being that you still need to write code to implement them and need to know about these changes
Yet another solution is adding it to providerWidget inside of a builder method, I think this might have some performance loss, not sure.

**Comment by vanlooverenkoen** [comment]
Extensions would be nice if the were fully supported 🙈 
But another drawback when using extensions is that your location class & theme data class if fetched from the tree every time you need to access these classes. It is better to fetch them once and keep them in memory during the build method. 

That is why were thinking to update the provider widget or add another widget in between. But maybe the mixins solution is a good one as well.
