### ISSUE TITLE
Version bump min iOS version to 12

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#134]
Set the min iOS version to our default one

**Comment by ikbendewilliam** [comment]
Do you mean by adding `platform :ios, '9.0'` or is there a variable that needs to be implemented here?

**Comment by vanlooverenkoen** [comment]
in xcode update the iOS min iOS version in the plist. 
![image](https://user-images.githubusercontent.com/21172855/105824972-5555a300-5fbf-11eb-8f64-8dd0a33c099b.png)
![image](https://user-images.githubusercontent.com/21172855/105825003-5d154780-5fbf-11eb-80b0-8e005a4e8641.png)
