### ISSUE TITLE
Use compute pools for json parsing

### ISSUE THREAD

**Issue by NicolaVerbeeck** [icapps/flutter-template#219]
Given the massive overhead of creating an isolate every time we parse json, we should use compute pools.

We should also add a 'compute' function with the regular compute function signature to pass to retrofit when so desired

Eg: https://pub.dev/packages/computer

**Comment by ikbendewilliam** [comment]
Is this still needed after the flutter 2.8.0 update?

**Comment by NicolaVerbeeck** [comment]
That needs to be benchmarked. Will get on it

**Comment by NicolaVerbeeck** [comment]
It is. Closing as we already have this in the codebase
