### ISSUE TITLE
To investigate: Logs colour after error stays red

### ISSUE THREAD

**Issue by ikbendewilliam** [icapps/flutter-template#232]
When running on Android, the logs turn red when an error has been encountered. They then stay red... 
This is probably related to a library (architecture, or other...)
iOS colour prints don't seem to be working?

**Comment by vanlooverenkoen** [comment]
I am using this so the app can still be used during debugging
```
  if (FlavorConfig.isDev()) {
    LoggingFactory.resetWithLogger(LoggerLogImpl(
      Logger(
        printer: OurPrettyPrinter(
          methodCount: 0,
          errorMethodCount: 5,
          lineLength: 50,
          colors: false,
          printEmojis: true,
          printTime: true,
        ),
        output: WrappingOutput(print),
      ),
      logNetworkInfo: true,
    ));
  }
```

**Comment by vanlooverenkoen** [comment]
Fixed by https://github.com/icapps/flutter-icapps-architecture/issues/78
