### ISSUE TITLE
fvm should be used for all scripts

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#240]

**Comment by vanlooverenkoen** [comment]
@ikbendewilliam found the problem with this. 
When you run a script that runs a dart script. you want to run fvm again to get all the packages. If you start that script with fvm -> you get this error:

```
fvm flutter packages get

Failed to execute command: fvm flutter packages get
Exception: Can't load Kernel binary: Invalid kernel binary format version.

Unhandled exception:
Exception: Can't load Kernel binary: Invalid kernel binary format version.

#0      executeCommand (file:///Users/vanlooverenkoen/Documents/work/flutter-template/tool/dart_tool/firebase_configurator.dart:179:7)
#1      main (file:///Users/vanlooverenkoen/Documents/work/flutter-template/tool/dart_tool/firebase_configurator.dart:146:3)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

```

**Comment by ikbendewilliam** [comment]
The issue isn't in the strip/remove script, but in the travis scripts
https://github.com/icapps/flutter-template/blob/bugfix/%23240-fvm-in-scripts/tool/travis/analyze.sh
Where you analyze with the latest available flutter version rather than the one set in .fvm `flutter analyze || exit -1;`

**Comment by vanlooverenkoen** [comment]
I see 2 options:
- we keep it as is: so we are forced to update to the latest version as soon as we create a new pr
- we move to fvm but add an extra verify job to check if the current version in fvm is the latest one.

What do you think?

**Comment by ikbendewilliam** [comment]
I'm not a huge fan of updating every new release immediately. Especially in random PR's that may try to fix a small issue. 
Leaving it like it is would be bad, since there is no indication why the build failed and only fails when flutter has breaking changes. 
So definitely fix the issue and if you prefer, we can add the check on the latest version

**Comment by vanlooverenkoen** [comment]
Fair point. Changing this to fvm it is. This will be however a bigger change than I initially thought :D so I closed my pr and will implement this after merging all the pr's and fix the travis build.
