### ISSUE TITLE
We should also have a permission screen that request permission to collect crash reports. To match gdpr compliance

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#242]
We should also have a permission screen that request permission to collect crash reports. To match gdpr compliance

_Originally posted by @vanlooverenkoen in https://github.com/icapps/flutter-template/issues/241#issuecomment-1090538688_

**Comment by rwillemsandroid** [comment]
Do we want to support the scenario where the user declines these analytics? Or do we block usage as long as this is not accepted?

**Comment by vanlooverenkoen** [comment]
I think we can always go forward. If it should be something different. The developer that is using our template project should fix that themselfs
