### ISSUE TITLE
System default language option is broken. 

### ISSUE THREAD

**Issue by rwillemsandroid** [icapps/flutter-template#284]
Selecting System default language option does not work.

It will fallback on on defaultLocale, which is hardcoded NL 

  static const defaultLocale = Locale.fromSubtags(languageCode: 'nl', scriptCode: null, countryCode: null);

**Comment by jorre127** [comment]
seems to work fine for me

**Comment by ikbendewilliam** [comment]
There is indeed a `defaultLocale` specified in locale_gen, but this is not used anymore
