### ISSUE TITLE
Remove routeName on a screen

### ISSUE THREAD

**Issue by luca-vz** [icapps/flutter-template#290]
On home, debug, splash -screen the routeName is still getting specified which is unnecessary because it isn't getting used.

**Comment by vanlooverenkoen** [comment]
@ikbendewilliam this is something that should be done in the get-x-navigator-generator right? 
I know it is possible to override it in the annotations. but i don't think we ever want to be using `-screen` suffixes

**Comment by ikbendewilliam** [comment]
That is something different, but a good addition to the generator indeed

**Comment by ikbendewilliam** [comment]
https://github.com/ikbendewilliam/get_x_navigation_generator/issues/1
