### ISSUE TITLE
Failed to run template project. Specify --flavor

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#3]
```Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...

The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: alpha, beta, dev, prod
You must specify a --flavor option to select one of them.
Finished with error: Gradle build aborted.
```

Add the option --flavor to make sure you run one of the allowed flavors

https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36

**Comment by vanlooverenkoen** [comment]
Supported flavors

-dev
-alpha
-beta
-prod

Edit your configuration:
![image](https://user-images.githubusercontent.com/21172855/59676305-8eb11480-91c7-11e9-92a7-9ec9e29440bc.png)

Add your flavor to the build flavor input field
![image](https://user-images.githubusercontent.com/21172855/59676336-a12b4e00-91c7-11e9-9421-77248b4a1768.png)

Extra:
When using multiple main.dart files you can specify the correct main.dart file in the dart entrypoint.

![image](https://user-images.githubusercontent.com/21172855/59676357-b607e180-91c7-11e9-8d2e-c01e4e540a8f.png)

**Comment by HannesVDB** [comment]
Die `--dev` kan ook enkel `dev` zijn lijkt me?

**Comment by vanlooverenkoen** [comment]
Yes inderdaad. Dat moet dev zijn. Ik pas de screenshot nog even aan.
