### ISSUE TITLE
Add support for android build tools 30

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#76]

**Comment by ikbendewilliam** [comment]
Is this compileSdkVersion and targetSdkVersion?

**Comment by vanlooverenkoen** [comment]
both compileSdkVersion & targetSdkVersion should be using 30.

And the build tools should be updated as well to 30.x.x

url_launcher package is not used in the template project. but on android, there were some problems with build tools 30 
in combination with url_launcher because an extra permission was needed if you wanted to check if you could launch an url. Maybe there are other problems as well.
